-- 멘토링 활동 기록 사진 첨부 (mentoring BC) — ActivityImage 엔티티 매핑 테이블.
-- 커밋 21c4595에서 엔티티(ActivityImage)만 추가되고 마이그레이션이 누락되어,
-- validate 환경(Testcontainers 통합 테스트)에서 "missing table [activity_images]"로 스키마 검증 실패했다.
-- 운영은 systemd ExecStart의 ddl-auto=update가 이미 자동 생성해 두었을 수 있으므로(스키마 드리프트),
-- IF NOT EXISTS로 멱등 작성 → 신규 DB(테스트)엔 생성, 이미 있는 운영엔 무해하게 스킵(배포 실패 방지).
create table if not exists activity_images (
    id          bigint generated by default as identity,
    activity_id bigint not null references mentoring_activities(id) on delete cascade,
    image_url   TEXT not null,
    order_index integer not null,
    primary key (id)
);

create index if not exists idx_activity_images_activity on activity_images(activity_id);
