-- V1 Baseline — 2026-05-22 시점 운영 RDS 스키마 (현재 JPA 엔티티에서 추출).
-- 운영 RDS에는 flyway baseline-on-migrate로 '실행 없이' 기록만 된다(이미 스키마 존재).
-- 신규 DB(로컬/CI)에서는 이 스크립트로 스키마를 생성한다.
-- 이후 스키마 변경은 V2+ 마이그레이션으로만 한다. (BC 리팩토링: 댓글/boardType 정리 등)


    create table anonymous_aliases (
        alias_number integer not null,
        context_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        context_type varchar(255) not null check (context_type in ('POST','QNA')),
        primary key (id),
        unique (context_type, context_id, member_id)
    );

    create table answer_likes (
        answer_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        primary key (id),
        unique (member_id, answer_id)
    );

    create table answer_translations (
        answer_id bigint not null,
        id bigint generated by default as identity,
        content TEXT not null,
        language varchar(255) not null check (language in ('KO','EN','ZH','VI','ES','MN')),
        primary key (id),
        unique (answer_id, language)
    );

    create table answers (
        is_adopted boolean not null,
        is_anonymous boolean not null,
        like_count integer not null,
        author_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        qna_id bigint not null,
        updated_at timestamp(6),
        primary key (id)
    );

    create table chat_messages (
        is_read boolean not null,
        is_system boolean not null,
        context_partner_id bigint,
        id bigint generated by default as identity,
        receiver_id bigint not null,
        sender_id bigint,
        sent_at timestamp(6),
        content TEXT not null,
        primary key (id)
    );

    create table comment_likes (
        comment_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        primary key (id),
        unique (member_id, comment_id)
    );

    create table comment_translations (
        comment_id bigint not null,
        id bigint generated by default as identity,
        content TEXT not null,
        language varchar(255) not null check (language in ('KO','EN','ZH','VI','ES','MN')),
        primary key (id),
        unique (comment_id, language)
    );

    create table comments (
        is_anonymous boolean not null,
        like_count integer not null,
        author_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        parent_id bigint,
        target_id bigint not null,
        updated_at timestamp(6),
        target_type varchar(255) not null check (target_type in ('POST','QNA','ANSWER')),
        primary key (id)
    );

    create table members (
        is_email_verified boolean not null,
        code_expired_at timestamp(6),
        created_at timestamp(6),
        id bigint generated by default as identity,
        refresh_token_expired_at timestamp(6),
        updated_at timestamp(6),
        email varchar(255) not null unique,
        email_verification_code varchar(255),
        password varchar(255) not null,
        refresh_token varchar(255),
        primary key (id)
    );

    create table mentor_mentee_matches (
        id bigint generated by default as identity,
        matched_at timestamp(6),
        mentee_id bigint not null,
        mentor_id bigint not null,
        semester varchar(255) not null,
        status varchar(255) not null check (status in ('ACTIVE','COMPLETED','CANCELLED')),
        primary key (id)
    );

    create table post_images (
        order_index integer not null,
        id bigint generated by default as identity,
        post_id bigint not null,
        image_url varchar(255) not null,
        primary key (id)
    );

    create table post_likes (
        created_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        post_id bigint not null,
        primary key (id),
        unique (member_id, post_id)
    );

    create table post_translations (
        id bigint generated by default as identity,
        post_id bigint not null,
        content TEXT not null,
        language varchar(255) not null check (language in ('KO','EN','ZH','VI','ES','MN')),
        title varchar(255) not null,
        primary key (id),
        unique (post_id, language)
    );

    create table posts (
        comment_count integer not null,
        is_anonymous boolean not null,
        like_count integer not null,
        author_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        board_type varchar(255) not null check (board_type in ('FRESHMAN','FREE','GRADUATE')),
        primary key (id)
    );

    create table profiles (
        admission_year integer not null,
        quiz_score float(53) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null unique,
        updated_at timestamp(6),
        department varchar(255) not null,
        language varchar(255) not null check (language in ('KO','EN','ZH','VI','ES','MN')),
        mentoring_role varchar(255) not null check (mentoring_role in ('MENTOR','MENTEE','NONE')),
        name varchar(255) not null,
        nationality varchar(255) not null,
        profile_image varchar(255),
        primary key (id)
    );

    create table qna_likes (
        created_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        qna_id bigint not null,
        primary key (id),
        unique (member_id, qna_id)
    );

    create table qna_translations (
        id bigint generated by default as identity,
        qna_id bigint not null,
        content TEXT not null,
        language varchar(255) not null check (language in ('KO','EN','ZH','VI','ES','MN')),
        title varchar(255) not null,
        primary key (id),
        unique (qna_id, language)
    );

    create table qnas (
        is_adopted boolean not null,
        is_anonymous boolean not null,
        like_count integer not null,
        author_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        primary key (id)
    );

    create table quiz_options (
        option_index integer not null,
        question_id bigint not null,
        option_text TEXT,
        primary key (option_index, question_id)
    );

    create table quiz_questions (
        answer_index integer not null,
        id bigint generated by default as identity,
        category varchar(255) not null,
        explanation TEXT,
        question TEXT not null,
        primary key (id)
    );

    create table quiz_results (
        correct_count integer not null,
        score float(53) not null,
        total_count integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        updated_at timestamp(6),
        primary key (id)
    );

    alter table if exists answer_likes 
       add constraint FKr5ed1ps65qfkhwvlg2jbbe1ip 
       foreign key (answer_id) 
       references answers;

    alter table if exists answer_likes 
       add constraint FK2dqo5jnjqv7xg8s9rhg7u52pi 
       foreign key (member_id) 
       references members;

    alter table if exists answer_translations 
       add constraint FK4w2n7j3lnvwx11pcb0t2lmttb 
       foreign key (answer_id) 
       references answers;

    alter table if exists answers 
       add constraint FKdbj8bulm1vs1tdymd8otmuont 
       foreign key (author_id) 
       references members;

    alter table if exists answers 
       add constraint FKr7pxf7vx6e1eas9p5ojih6nuh 
       foreign key (qna_id) 
       references qnas;

    alter table if exists chat_messages 
       add constraint FKhyv0wyy5huj3gwkru2ol6srks 
       foreign key (context_partner_id) 
       references members;

    alter table if exists chat_messages 
       add constraint FKmh3qvfjsjms66wvv3jxgumpyy 
       foreign key (receiver_id) 
       references members;

    alter table if exists chat_messages 
       add constraint FKmf86klrrgnufxig1bgb94kafu 
       foreign key (sender_id) 
       references members;

    alter table if exists comment_likes 
       add constraint FK3wa5u7bs1p1o9hmavtgdgk1go 
       foreign key (comment_id) 
       references comments;

    alter table if exists comment_likes 
       add constraint FKq6gltbxc24mdpub8fpe4ms8wf 
       foreign key (member_id) 
       references members;

    alter table if exists comment_translations 
       add constraint FKhp8qkwsxxul4mnsy8ulyd269a 
       foreign key (comment_id) 
       references comments;

    alter table if exists comments 
       add constraint FK1fyfbq4q0rlrs4q7mnxu2l3fl 
       foreign key (author_id) 
       references members;

    alter table if exists comments 
       add constraint FKlri30okf66phtcgbe5pok7cc0 
       foreign key (parent_id) 
       references comments;

    alter table if exists mentor_mentee_matches 
       add constraint FKa40r6n4xb8tt8i7dxfrx7wmub 
       foreign key (mentee_id) 
       references members;

    alter table if exists mentor_mentee_matches 
       add constraint FKepxnapfwy5wf1mjruad2gj2u 
       foreign key (mentor_id) 
       references members;

    alter table if exists post_images 
       add constraint FKo1i5va2d8de9mwq727vxh0s05 
       foreign key (post_id) 
       references posts;

    alter table if exists post_likes 
       add constraint FKsr9uiilpnflc32a04yyx7bun 
       foreign key (member_id) 
       references members;

    alter table if exists post_likes 
       add constraint FKa5wxsgl4doibhbed9gm7ikie2 
       foreign key (post_id) 
       references posts;

    alter table if exists post_translations 
       add constraint FK4jvnpdlk6xuibg8kgabg1mkvt 
       foreign key (post_id) 
       references posts;

    alter table if exists posts 
       add constraint FKi5bu1f3ok7idxb9a83e2ebru8 
       foreign key (author_id) 
       references members;

    alter table if exists profiles 
       add constraint FK3hr5spee9cqr8l655j980b20j 
       foreign key (member_id) 
       references members;

    alter table if exists qna_likes 
       add constraint FKiegagrslqeoqfdthdjh99oaw6 
       foreign key (member_id) 
       references members;

    alter table if exists qna_likes 
       add constraint FKp7or2tp3uwwd0qmbtbxhy10xy 
       foreign key (qna_id) 
       references qnas;

    alter table if exists qna_translations 
       add constraint FKashkdleo15x8vsgx8l9uwgw5a 
       foreign key (qna_id) 
       references qnas;

    alter table if exists qnas 
       add constraint FKbbnna3bbmibic2y7giodlkjp9 
       foreign key (author_id) 
       references members;

    alter table if exists quiz_options 
       add constraint FKhkuvmd7qk1lmtq3hy9htpinkr 
       foreign key (question_id) 
       references quiz_questions;

    alter table if exists quiz_results 
       add constraint FKeoghccjhmpo090q9gm4nyvjbt 
       foreign key (member_id) 
       references members;
