-- 멘토링 활동 기록 (mentoring BC).
-- MentoringActivity 엔티티 매핑 테이블. 매칭 당사자(멘토/멘티)가 활동 내용을 기록한다.
-- match_id/author_id 는 ID 참조(다른 BC를 엔티티로 직접 참조하지 않음).
create table mentoring_activities (
    id         bigint generated by default as identity,
    match_id   bigint not null,
    author_id  bigint not null,
    title      varchar(255) not null,
    content    TEXT not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);
