-- 멤버 뱃지 (campusguide BC).
-- MemberBadge 엔티티 매핑 테이블. 카테고리 퀴즈 통과 시 획득하는 뱃지를 기록한다.
-- MemberBadge가 BaseTimeEntity를 상속하므로 created_at/updated_at 컬럼이 필요하다
-- (created_at = 획득 시각, BadgeResponse가 earnedAt으로 노출). member_id는 ID 참조.
create table member_badges (
    id         bigint generated by default as identity,
    member_id  bigint not null,
    badge_id   varchar(50) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    constraint uq_member_badge unique (member_id, badge_id)
);
